org.slf4j.simpleLogger.defaultLogLevel=info
org.slf4j.simpleLogger.log.org.eclipse.jetty=warn
org.slf4j.simpleLogger.log.io.javalin=warn
org.slf4j.simpleLogger.log.org.drools=warn
org.slf4j.simpleLogger.log.org.kie=warn
